image: wraithbb/lynxware-cpp

stages:
  - build

before_script:
  - rm -rf ../ngengine
  - echo -e $SSH_KEY_NGENGINE > ~/.ssh/id_rsa
  - echo -e "Host gitlab.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
  - git clone --recursive git@gitlab.com:lynxware/ngengine.git ../ngengine

build-all-examples:
  stage: build
  script:
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4