stages:
  - build

before_script:
  - rm -rf ../ngengine
  - echo -e $SSH_KEY_NGENGINE > ~/.ssh/id_rsa
  - echo -e "Host gitlab.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
  - git clone git@gitlab.com:lynxware/ngengine.git ../ngengine

build:
  stage: build
  script:
    - ls -la
    - mkdir build/
    - cmake ..
    - make