stages:
  - build

before_script:
  - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
  - git submodule update --init 

build:
  stage: build
  script:
    - git clone git@gitlab.com:lynxware/ngengine.git ../ngengine
    - mkdir build/
    - cmake ..
    - make