image: wraithbb/lynxware-cpp

stages:
  - build

before_script:
  - rm -rf ../ngengine
  - echo -e $SSH_KEY_NGENGINE > ~/.ssh/id_rsa
  - echo -e "Host gitlab.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
  - git clone --recursive git@gitlab.com:lynxware/ngengine.git ../ngengine

ngengine-waterexample:
  stage: build
  script:
    - cd ngengine-waterexample/
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4

ngengine-colored-triangle:
  stage: build
  script:
    - cd ngengine-colored-triangle/
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4

ngengine-ripple-deformation:
  stage: build
  script:
    - cd ngengine-ripple-deformation/
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4

ngengine-subdivision-geometry:
  stage: build
  script:
    - cd ngengine-subdivision-geometry/
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4

ngengine-subdivision-geometry-instanced:
  stage: build
  script:
    - cd ngengine-subdivision-geometry-instanced/
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4

ngengine-blank:
  stage: build
  script:
    - cd ngengine-blank/
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4