stages:
  - build

build:
  stage: build
  script:
    - echo $SSH_KEY_NGENGINE > ~/.ssh/id_rsa
    - echo -e "Host gitlab.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
    - git clone git@gitlab.com:lynxware/ngengine.git ../ngengine
    - mkdir build/
    - cmake ..
    - make